### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by MaxCarthy** [YT-Advanced/YT-Advanced#1]
Hi sorry to bother hope you don't mind
I really like the whitelist feature that revanced extended had and saw you opened a issue about it
i was wondering if you know how it worked as any channel that was already whitelisted still works
so was thinking if you know how it work, because maybe if the app already has the channel id it will work, so that means a patch where we can manuely add the channel id will work
Thanks in advance

**Comment by YT-Advanced** [comment]
@MaxCarthy Sorry because I'm too busy.
Revanced Extended use Youtube api v2 to get the video infomation. Unluckily, Youtube have discontinued api v2 and switch to api v3. That is why the whitelist feature stop work.
And when I suggest inotia00 about the new method, it have some problem:
1. If we use api v3, we don't have Youtube api key, hope somebody donate the key :))))
2. If we use oembed method, the exclude will not work because video loaded before SponsorBlock started.
So now I (and also inotia00) can't implement it.
