### ISSUE TITLE
Please read the about in rvx repos

### ISSUE THREAD

**Issue by 8cAyqpVKio** [YT-Advanced/YT-Advanced#11]
Link: https://github.com/YT-Advanced/rvx/releases

You are using revanced team's patches and offering prebuilt apks, this is putting revanced team's patches in risk.

https://github.com/ReVanced/revanced-discussions/discussions/1002

**Comment by iloveviolin** [comment]
He wont stop, no matter how much you tell him. I already warned people on reddit about him and I got yelled at.

**Comment by YT-Advanced** [comment]
Removed rvx repos and only keep Debug repos for my Debug purpose. Donate me a Github Pro subscription if you don't want to see this repos too.
Regard !

**Comment by iloveviolin** [comment]
So now youre blackmailing? What the actual fuck! I will report your github repo and hope that you get banned. This is not how you treat people.

**Comment by YT-Advanced** [comment]
> So now youre blackmailing? What the actual fuck! I will report your github repo and hope that you get banned. This is not how you treat people.

Huh, Github didn't allow to use Github Action in Private repos. That's why I asked you.
Good luck, in the past Cuynu have reported me but he can't, hope you can

**Comment by YT-Advanced** [comment]
And also here is some more:
First, your Reddit and Github account created recently (when I post the first post introduce my patch in Reddit) ?
Second, all member in RVX Telegram Channel know about me, but you are not, you didn't know about RVX yet.
Third, I have replied in Reddit then no answer ? You can't answer because you just want to stop me.
