### ISSUE TITLE
Overlay buttons are not hidden when swiping the seekbar with new thumbnail preview

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#7]
![Screenshot_20230809_113425_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/130296934/45931120-ad9d-4e44-865b-4f3425b77486)

This bug is related with:
https://github.com/inotia00/ReVanced_Extended/issues/504
https://github.com/inotia00/ReVanced_Extended/issues/631

inotia fixed this bug but I think they forgot to apply the fix to the new thumbnail preview.

**Comment by YT-Advanced** [comment]
Right, inotia00 forgot it. I will try to fix it

**Comment by YT-Advanced** [comment]
@federicogith I'm here to notify that it's fixed in my latest patch. Try right now !

**Comment by federicogith** [comment]
@YT-Advanced I just checked it, it isn't fixed yet.

**Comment by YT-Advanced** [comment]
@federicogith I have checked again and it only hide on my tablet .-. Sorry because I forgot to test on phone too

**Comment by YT-Advanced** [comment]
@federicogith Hello. When you are playing a video then scroll, the patch think you are playing video so the icon showed. If you pause video then scroll, you will not face with this problem. I have 2 fix for this problem but all are not quite good:
1. Remove function check if you are playing video will make the overlay button hide when finished scroll.
2. Pause video then perform scroll, it may annoy for some user because we need to mannual resume the video.

If anyone can do it, please leave a Pull Request

**Comment by YT-Advanced** [comment]
Fixed in lastest version
